import type { Challenge } from './types';
import { pickLocale } from '../tutorial/i18n';

const TEXTS = pickLocale({
  en: {
    c1_title: 'Find emails in text',
    c1_summary: 'Extract every email address from a paragraph.',
    c1_description: [
      '**Goal**: write a pattern that finds every email-like string in **plain text**.',
      '',
      'Each test passes if at least one match is found (or zero, for noMatch cases).',
      '',
      'Common shape: `local@host.tld`, where local may contain letters, digits, `.`, `_`, `+`, `-`; host is `domain.tld`.',
    ].join('\n'),
    c1_cases: [
      'Two emails in a paragraph',
      'Plus alias / subdomain',
      'No email at all',
      'Missing TLD',
      'Just an @ sign',
    ],
    c1_hints: [
      'Use `\\b` boundaries to avoid bleeding into neighbors.',
      'Local part `[\\w.+-]+`; host `[\\w-]+`; TLD at least 2 letters `[a-zA-Z]{2,}`.',
    ],
    c1_explanation: '`\\b` boundaries + local + `@` + host + TLD with at least 2 letters.',

    c2_title: 'Strict HTTPS URL',
    c2_summary: 'Whole-string check that the input is a valid `https://` URL (no other protocols).',
    c2_description: [
      '**Goal**: validate that the **whole** string is a valid `https://...` URL.',
      '',
      '⚠️ This is **whole-string** validation: anchor with `^...$`, otherwise `https://example.com` inside `http://example.com` etc. would pass by accident.',
    ].join('\n'),
    c2_cases: [
      'Minimal https URL',
      'Subdomain + path + query',
      'http should fail',
      'ftp should fail',
      'https with no host',
      'Bare host',
    ],
    c2_hints: [
      'Start with `^https:\\/\\/`.',
      'Host must contain at least one `.` and length ≥ 1.',
      'Optional path/query: `(?:\\/.*)?`.',
    ],
    c2_explanation: '`^https:\\/\\/` locks the protocol; host has dot + TLD; optional path with `(?:\\/[^\\s]*)?` and final `$`.',

    c3_title: 'IPv4 address (lenient)',
    c3_summary: 'Match four dot-separated decimal segments (no 0–255 range check).',
    c3_description: [
      '**Goal**: validate "four 1–3 digit segments separated by `.`". You do **not** need to enforce 0–255 ranges.',
      '',
      'Use `^...$` for whole-string validation.',
    ].join('\n'),
    c3_cases: [
      'Common private IP',
      'All zeros',
      'All 255s',
      'Only 3 segments',
      'Five segments',
      'Letters in segment',
      'Segment too long',
    ],
    c3_hints: ['`\\d{1,3}` is 1 to 3 digits.', 'Four segments joined by `\\.`.'],
    c3_explanation: 'Four 1–3 digit segments; `.` must be escaped.',

    c4_title: 'Hex color',
    c4_summary: 'Accept `#abc` shorthand or `#aabbcc` long form.',
    c4_description: [
      '**Goal**: validate a CSS hex color:',
      '',
      '- starts with `#`',
      '- followed by **3** or **6** hex digits (`0-9` / `a-f` / `A-F`)',
      '',
      'Use `^...$`.',
    ].join('\n'),
    c4_cases: [
      '3-digit shorthand',
      '3-digit uppercase',
      '6-digit long form',
      'Mixed case',
      'Missing #',
      'Non-hex chars',
      '4 digits',
      '5 digits',
    ],
    c4_hints: ['Character class `[\\da-fA-F]`.', 'Group + `|` to accept 3 or 6: `([\\da-fA-F]{3}|[\\da-fA-F]{6})`.'],
    c4_explanation: 'Putting `{3}` before `{6}` would let `#abc123` match only `#abc` — `^...$` plus `|` ensures the whole string is consumed.',

    c5_title: 'ISO date format',
    c5_summary: '`YYYY-MM-DD`, format only — not real-date validation.',
    c5_description: [
      '**Goal**: check if the whole string follows `YYYY-MM-DD`: 4-digit year, 2-digit month, 2-digit day.',
      '',
      'No need to validate "Feb 30" — only positions and separators.',
    ].join('\n'),
    c5_cases: [
      'Normal date',
      'Beginning of century',
      'Single-digit month',
      'Slash separators',
      'Trailing junk',
      'Empty string',
    ],
    c5_hints: ['Year `\\d{4}`, month/day `\\d{2}` each, joined by `-`.'],

    c6_title: 'Strong password (lookahead)',
    c6_summary: 'At least 8 chars, must contain **both** a letter and a digit.',
    c6_description: [
      '**Goal**: validate a strong password:',
      '',
      '- length ≥ 8',
      '- must contain **both** at least one letter and one digit',
      '',
      '💡 Multiple independent conditions like this are cleanest with **lookahead**: each `(?=...)` checks one without consuming the cursor.',
    ].join('\n'),
    c6_cases: [
      'Letter + digit mix',
      'Long with digit',
      'Has special chars',
      'Too short',
      'Letters only',
      'Digits only',
      'Empty string',
    ],
    c6_hints: [
      '`(?=.*[A-Za-z])` asserts "a letter exists somewhere".',
      '`(?=.*\\d)` asserts "a digit exists somewhere".',
      'Chain both lookaheads, then `^.{8,}$` for length.',
    ],
    c6_explanation: 'Two zero-width lookaheads check letter and digit; the body `.{8,}` enforces length — all three must hold.',

    c7_title: 'North American phone number',
    c7_summary: 'Accept the four common formats: parens, dashes, dots, optional country code.',
    c7_description: [
      '**Goal**: validate a North American phone number. Common shapes:',
      '',
      '- `(415) 555-2671`',
      '- `415-555-2671`',
      '- `415.555.2671`',
      '- `415 555 2671`',
      '- `4155552671`',
      '- Optional `+1 ` or `+1-` prefix',
      '',
      '⚠️ Whole-string validation: anchor with `^...$`.',
    ].join('\n'),
    c7_cases: [
      'Parens + dashes',
      'Dash separators',
      'Dot separators',
      'Spaces + country code',
      'Bare digits',
      'Wrong middle length',
      'Last segment too long',
      'Letters',
      'Empty string',
    ],
    c7_hints: [
      'Optional country code: `(?:\\+1[ -]?)?`',
      'Area code: `\\(?\\d{3}\\)?` (parens optional)',
      'Separators: `[ .-]?`',
    ],
    c7_explanation: 'Optional country code + 3-digit area code + optional separator + 3 + optional separator + 4. This pattern cannot enforce paired parens but blocks most misalignments.',

    c8_title: 'URL slug',
    c8_summary: 'Lowercase letters / digits / single `-`; no leading/trailing or doubled dashes.',
    c8_description: [
      '**Goal**: validate a URL slug:',
      '',
      '- only lowercase letters, digits, `-`',
      '- **must not** start or end with `-`',
      '- **must not** contain `--`',
      '',
      'Use `^...$` for whole-string validation.',
    ].join('\n'),
    c8_cases: [
      'Single word',
      'With dashes',
      'Mixed digits',
      'Uppercase not allowed',
      'Leading dash',
      'Trailing dash',
      'Doubled dash',
      'Contains space',
      'Empty string',
    ],
    c8_hints: [
      'Idea: `[a-z0-9]+` first segment, then repeat `(-[a-z0-9]+)*`.',
      'Encode the rules into the structure — no separate checks needed.',
    ],
    c8_explanation: 'Structural enforcement: every `-` **must** be followed by at least one alphanumeric, ruling out leading/trailing/doubled dashes.',

    c9_title: 'Extract Markdown links',
    c9_summary: 'Find every `[text](url)` link in the text.',
    c9_description: [
      '**Goal**: extract every `[text](url)` Markdown link from a paragraph.',
      '',
      'find-mode: a test passes if at least one match is found; if no valid link exists, the result must be empty (noMatch).',
      '',
      "⚠️ Don't accept unclosed lookalikes (e.g. `[bad](still here`).",
    ].join('\n'),
    c9_cases: [
      'One link',
      'Two adjacent links',
      'Link in CJK text',
      'No link',
      'Just brackets',
      'Unclosed paren',
    ],
    c9_hints: [
      'Use `[^\\]]+` for text — safer than `.+?`.',
      'URL similarly: `[^)]+`, with **mandatory** closing `)`.',
    ],
    c9_explanation: '`[^\\]]+` clamps the text (no `]` allowed); `[^)]+` clamps the url; the surrounding `\\[ \\] \\( \\)` forces both pairs.',

    c10_title: 'CSS class name',
    c10_summary: 'Letter/`_` start (or `-` then letter/`_`); rest may include letters, digits, `_`, `-`.',
    c10_description: [
      '**Goal**: validate a CSS class name (simplified):',
      '',
      '- first char must be a letter or `_`, **or** a `-` followed by letter/`_`',
      '- subsequent chars: letters / digits / `_` / `-`',
      '',
      '⚠️ Whole-string validation.',
    ].join('\n'),
    c10_cases: [
      'Plain word',
      'BEM style',
      'Underscore start',
      'Negative prefix',
      'Mixed case + digit',
      'Starts with digit',
      'Doubled dash start',
      'Contains space',
      'Has !',
      'Empty string',
    ],
    c10_hints: ['Optional leading `-?`', 'Then required letter/underscore: `[A-Za-z_]`', 'Then any tail: `[A-Za-z0-9_-]*`'],
    c10_explanation: 'Optional `-` + required letter/underscore + any number of legal tail characters covers most real-world names.',

    c11_title: 'UUID v4',
    c11_summary: '8-4-4-4-12 hex; version digit is `4`, variant digit is 8/9/a/b.',
    c11_description: [
      '**Goal**: validate a **v4** UUID:',
      '',
      '`xxxxxxxx-xxxx-4xxx-Yxxx-xxxxxxxxxxxx`',
      '',
      '- 5 hex segments of length 8/4/4/4/12 (any case)',
      '- segment 3 starts with `4` (version)',
      '- segment 4 starts with `8`/`9`/`a`/`b`/`A`/`B` (variant)',
      '',
      '⚠️ Whole-string validation.',
    ].join('\n'),
    c11_cases: [
      'Standard v4',
      'v4 uppercase',
      'Another v4',
      'Version digit is 1',
      'Wrong variant',
      'Wrong segment length',
      'Non-hex char',
      'Random string',
      'Empty string',
    ],
    c11_hints: [
      'Skeleton: `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`',
      'Version: replace the first char of segment 3 with literal `4`.',
      'Variant: first char of segment 4 is `[89abAB]`.',
    ],
    c11_explanation: 'Hard-coding the version digit (`4`) and the variant digit (`[89abAB]`) is the standard pattern for quick UUID-version validation.',
  },
  zh: {
    c1_title: '在文本里抓邮箱',
    c1_summary: '从一段段落中提取所有邮箱地址。',
    c1_description: [
      '**目标**：写一个 pattern，**从一段普通文本里**找出所有看起来像邮箱的字符串。',
      '',
      '只要每个测试输入里至少抓到一个匹配（或者根本没匹配，对应 noMatch），就算过。',
      '',
      '常见结构：`local@host.tld`，其中 local 可能含字母数字 / `.` / `_` / `+` / `-`，host 是 `域.顶级`。',
    ].join('\n'),
    c1_cases: [
      '段落里两个邮箱',
      '加号 / 子域名',
      '完全没有邮箱',
      '缺少顶级域',
      '只有 @',
    ],
    c1_hints: [
      '用 `\\b` 加边界，避免漏抓或多抓。',
      '本地部分可用 `[\\w.+-]+`，域名段用 `[\\w-]+`，顶级域至少 2 字母 `[a-zA-Z]{2,}`。',
    ],
    c1_explanation: '`\\b` 边界 + 本地段 + `@` + 主机段 + 至少 2 字母的 TLD。',

    c2_title: '严格 HTTPS URL',
    c2_summary: '判断整串是不是合法的 https:// 开头 URL（不允许其它协议）。',
    c2_description: [
      '**目标**：判断**整串**是否为合法的 `https://...` URL。',
      '',
      '⚠️ 这是**全串校验**：请使用 `^...$` 锚点，否则 `http://example.com` 里的 `https://example.com` 之类就会"误伤"。',
    ].join('\n'),
    c2_cases: [
      '最简 https URL',
      '带子域 + 路径 + 查询串',
      'http 不行',
      'ftp 不行',
      'https 后面没主机',
      '裸主机',
    ],
    c2_hints: [
      '需要 `^https:\\/\\/` 开头。',
      '主机段至少要包含一个 `.`，长度 ≥ 1。',
      '路径 / 查询串可选，可用 `(?:\\/.*)?`。',
    ],
    c2_explanation: '`^https:\\/\\/` 锁定协议，主机段含点和 TLD，可选路径用 `(?:\\/[^\\s]*)?`，结尾 `$`。',

    c3_title: 'IPv4 地址（宽松版）',
    c3_summary: '识别四段点分十进制（不要求 0–255 范围）。',
    c3_description: [
      '**目标**：判断输入是不是合法的 IPv4 字面量——只要"4 段、由 `.` 分隔、每段是 1–3 位数字"即可，**不要求**每段在 0–255 范围内。',
      '',
      '使用 `^...$` 做整串校验。',
    ].join('\n'),
    c3_cases: [
      '常见私网 IP',
      '全 0',
      '全 255',
      '只有 3 段',
      '5 段',
      '段里含字母',
      '段太长',
    ],
    c3_hints: ['`\\d{1,3}` 表示 1 到 3 位数字。', '4 段中间用 `\\.` 隔开。'],
    c3_explanation: '4 段 1–3 位数字，`.` 必须转义。',

    c4_title: 'Hex 颜色码',
    c4_summary: '`#abc` 短写或 `#aabbcc` 长写都接受。',
    c4_description: [
      '**目标**：判断输入是不是合法的 CSS hex 颜色码：',
      '',
      '- 必须以 `#` 开头',
      '- 后面是 **3 位**或 **6 位**十六进制（`0-9` / `a-f` / `A-F`）',
      '',
      '使用 `^...$` 锚点。',
    ].join('\n'),
    c4_cases: [
      '3 位短写',
      '3 位大写',
      '6 位长写',
      '6 位混合大小写',
      '没有 #',
      '非 hex 字符',
      '4 位',
      '5 位',
    ],
    c4_hints: ['字符类 `[\\da-fA-F]`。', '用分组 + `|` 让 3 位或 6 位都接受：`([\\da-fA-F]{3}|[\\da-fA-F]{6})`。'],
    c4_explanation: '注意 `{3}` 在 `{6}` 之前会让 3 位先匹配，导致 `#abc123` 只匹到 `#abc`——所以必须 `^...$` 配合 `|` 让整串都对齐。',

    c5_title: 'ISO 日期格式',
    c5_summary: '`YYYY-MM-DD`，仅校验格式不校验真实日期。',
    c5_description: [
      '**目标**：判断整串是不是 `YYYY-MM-DD` 这种格式：4 位年份 - 2 位月 - 2 位日。',
      '',
      '不需要校验"2 月没有 30 号"——只校验位数和分隔符。',
    ].join('\n'),
    c5_cases: [
      '正常日期',
      '世纪初',
      '单位数月份',
      '斜杠分隔',
      '后面有杂物',
      '空串',
    ],
    c5_hints: ['年份是 `\\d{4}`，月日各 `\\d{2}`，中间 `-`。'],

    c6_title: '强密码（lookahead 实战）',
    c6_summary: '至少 8 字符，必须**同时**含字母和数字。',
    c6_description: [
      '**目标**：判断整串是不是合格的强密码：',
      '',
      '- 长度 ≥ 8',
      '- 必须**同时**包含至少一个字母和至少一个数字',
      '',
      '💡 这种"多个独立条件都得满足"的需求，用 **lookahead** 最干净——一组 `(?=...)` 验证一个条件，不消耗指针。',
    ].join('\n'),
    c6_cases: [
      '字母+数字混合',
      '长串带数字',
      '带特殊字符',
      '太短',
      '只有字母',
      '只有数字',
      '空串',
    ],
    c6_hints: [
      '`(?=.*[A-Za-z])` 断言"某处有字母"。',
      '`(?=.*\\d)` 断言"某处有数字"。',
      '把两个 lookahead 串在一起，再加上 `^.{8,}$` 控制长度。',
    ],
    c6_explanation: '两个零宽 lookahead 各自检查字母和数字，主体 `.{8,}` 控制长度——三者并存。',

    c7_title: '北美电话号码',
    c7_summary: '常见 4 种格式都接受：括号、横线、点、加国家码。',
    c7_description: [
      '**目标**：判断**整串**是不是合法的北美电话号码。常见写法：',
      '',
      '- `(415) 555-2671`',
      '- `415-555-2671`',
      '- `415.555.2671`',
      '- `415 555 2671`',
      '- `4155552671`',
      '- 可选前缀 `+1 ` 或 `+1-`',
      '',
      '⚠️ 整串校验，请加 `^...$`。',
    ].join('\n'),
    c7_cases: [
      '括号 + 横线',
      '横线分隔',
      '点分隔',
      '空格 + 国家码',
      '纯数字',
      '中段位数不对',
      '尾段多了一位',
      '字母',
      '空串',
    ],
    c7_hints: [
      '可选国家码：`(?:\\+1[ -]?)?`',
      '区号：`\\(?\\d{3}\\)?`（左右括号都可选）',
      '中间分隔符：`[ .-]?`',
    ],
    c7_explanation: '把"可选国家码 + 3 位区号 + 可选分隔符 + 3 位 + 可选分隔符 + 4 位"串起来。注意这个 pattern 对"括号必须配对"做不到——但能挡住绝大多数错位。',

    c8_title: 'URL Slug',
    c8_summary: '只能小写字母 / 数字 / 单个 `-`，不许首尾或连续短横线。',
    c8_description: [
      '**目标**：判断输入是不是合法的 URL slug：',
      '',
      '- 只能含小写字母、数字、`-`',
      '- **不能**以 `-` 开头或结尾',
      '- **不能**连续 `--`',
      '',
      '使用 `^...$` 做整串校验。',
    ].join('\n'),
    c8_cases: [
      '单词',
      '带短横',
      '混数字',
      '大写不行',
      '前导短横',
      '尾随短横',
      '连续短横',
      '含空格',
      '空串',
    ],
    c8_hints: [
      '思路：首段 `[a-z0-9]+`，可重复的"`-` + 一段"用 `(-[a-z0-9]+)*`。',
      '把规则编进结构里，就不需要单独检查首尾或连续短横。',
    ],
    c8_explanation: '通过结构强制：每个 `-` 后面**必须**跟着至少一个字母数字，自然就排除了前导/尾随/连续的情况。',

    c9_title: '抽取 Markdown 链接',
    c9_summary: '在文本里找出所有 `[text](url)` 形式的链接。',
    c9_description: [
      '**目标**：从一段文本里**抽取**所有 Markdown 链接 `[text](url)`。',
      '',
      'find-mode：每个测试输入只要找到至少一个匹配就算 match；如果原本没有合法链接，则应一个都不匹配（noMatch）。',
      '',
      '⚠️ "看起来像但没闭合"的写法不算（比如 `[bad](still here`）。',
    ].join('\n'),
    c9_cases: [
      '一条链接',
      '两条相邻',
      '中文文本里的链接',
      '没有链接',
      '只有方括号',
      '括号未闭合',
    ],
    c9_hints: [
      '文本部分用取反字符类 `[^\\]]+`，比 `.+?` 稳。',
      'URL 部分类似：`[^)]+`，并且**必须**有闭合的 `)`。',
    ],
    c9_explanation: '`[^\\]]+` 锁住 text（不能跨过 `]`），`[^)]+` 锁住 url（不能跨过 `)`），最外层的 `\\[ \\] \\( \\)` 强制成对出现。',

    c10_title: 'CSS 类名',
    c10_summary: '简化版：字母/`_` 开头（或 `-` + 字母/`_`），后续允许字母数字 / `_` / `-`。',
    c10_description: [
      '**目标**：判断输入是不是一个合法的 CSS 类名（简化规则）：',
      '',
      '- 第一个字符必须是字母或 `_`，**或者**一个 `-` 后再跟字母/`_`',
      '- 后续可以是字母 / 数字 / `_` / `-`',
      '',
      '⚠️ 整串校验。',
    ].join('\n'),
    c10_cases: [
      '普通单词',
      'BEM 写法',
      '下划线开头',
      '负前缀',
      '混大写数字',
      '数字开头',
      '双短横开头',
      '含空格',
      '感叹号',
      '空串',
    ],
    c10_hints: [
      '先吃可选的 `-?`',
      '然后必须是字母或 `_`：`[A-Za-z_]`',
      '后续：`[A-Za-z0-9_-]*`',
    ],
    c10_explanation: '前导 `-` 可选 + 必须的字母/下划线 + 任意多后续合法字符，覆盖大多数实战命名。',

    c11_title: 'UUID v4',
    c11_summary: '8-4-4-4-12 的 hex；版本位是 4，variant 位是 8/9/a/b。',
    c11_description: [
      '**目标**：判断输入是不是合法的 **v4** UUID。形式：',
      '',
      '`xxxxxxxx-xxxx-4xxx-Yxxx-xxxxxxxxxxxx`',
      '',
      '- 5 段，长度依次 8/4/4/4/12，全部 hex（大小写都可以）',
      '- 第 3 段以 `4` 开头（版本位）',
      '- 第 4 段以 `8`/`9`/`a`/`b`/`A`/`B` 开头（variant 位）',
      '',
      '⚠️ 整串校验。',
    ].join('\n'),
    c11_cases: [
      '标准 v4',
      'v4 大写',
      '另一个 v4',
      '版本位是 1',
      'variant 不对',
      '段长不对',
      '含非 hex',
      '随机字符串',
      '空串',
    ],
    c11_hints: [
      '基本骨架：`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`',
      '版本位：第 3 段第一个字符替成字面量 `4`',
      'Variant：第 4 段第一个字符是 `[89abAB]`',
    ],
    c11_explanation: '把版本位（`4`）和 variant 位（`[89abAB]`）当成"硬编码字面量"嵌进去，是 UUID 各版本快速校验的常用模式。',
  },
});

export const CHALLENGES: Challenge[] = [
  {
    id: 'email-find',
    title: TEXTS.c1_title,
    summary: TEXTS.c1_summary,
    description: TEXTS.c1_description,
    difficulty: 'beginner',
    starterPattern: '',
    starterFlags: 'g',
    testCases: [
      { label: TEXTS.c1_cases[0], input: 'Reach me at hello@example.com or sales@example.org.', expect: 'match' },
      { label: TEXTS.c1_cases[1], input: 'Send to alice+filter@mail.sub.example.io please.', expect: 'match' },
      { label: TEXTS.c1_cases[2], input: 'No email is mentioned in this paragraph.', expect: 'noMatch' },
      { label: TEXTS.c1_cases[3], input: 'broken: bob@host', expect: 'noMatch' },
      { label: TEXTS.c1_cases[4], input: 'just an @ sign here', expect: 'noMatch' },
    ],
    hints: TEXTS.c1_hints,
    idealSolution: {
      pattern: '\\b[\\w.+-]+@[\\w-]+\\.[a-zA-Z]{2,}\\b',
      flags: 'g',
      explanation: TEXTS.c1_explanation,
    },
  },
  {
    id: 'https-url',
    title: TEXTS.c2_title,
    summary: TEXTS.c2_summary,
    description: TEXTS.c2_description,
    difficulty: 'intermediate',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c2_cases[0], input: 'https://example.com', expect: 'match' },
      { label: TEXTS.c2_cases[1], input: 'https://sub.example.com/api?token=abc&x=1', expect: 'match' },
      { label: TEXTS.c2_cases[2], input: 'http://example.com', expect: 'noMatch' },
      { label: TEXTS.c2_cases[3], input: 'ftp://example.com', expect: 'noMatch' },
      { label: TEXTS.c2_cases[4], input: 'https://', expect: 'noMatch' },
      { label: TEXTS.c2_cases[5], input: 'example.com', expect: 'noMatch' },
    ],
    hints: TEXTS.c2_hints,
    idealSolution: {
      pattern: '^https:\\/\\/[\\w.-]+\\.[a-zA-Z]{2,}(?:\\/[^\\s]*)?$',
      explanation: TEXTS.c2_explanation,
    },
  },
  {
    id: 'ipv4',
    title: TEXTS.c3_title,
    summary: TEXTS.c3_summary,
    description: TEXTS.c3_description,
    difficulty: 'beginner',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c3_cases[0], input: '192.168.1.1', expect: 'match' },
      { label: TEXTS.c3_cases[1], input: '0.0.0.0', expect: 'match' },
      { label: TEXTS.c3_cases[2], input: '255.255.255.255', expect: 'match' },
      { label: TEXTS.c3_cases[3], input: '1.2.3', expect: 'noMatch' },
      { label: TEXTS.c3_cases[4], input: '1.2.3.4.5', expect: 'noMatch' },
      { label: TEXTS.c3_cases[5], input: 'a.b.c.d', expect: 'noMatch' },
      { label: TEXTS.c3_cases[6], input: '1.2.3.4567', expect: 'noMatch' },
    ],
    hints: TEXTS.c3_hints,
    idealSolution: {
      pattern: '^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$',
      explanation: TEXTS.c3_explanation,
    },
  },
  {
    id: 'hex-color',
    title: TEXTS.c4_title,
    summary: TEXTS.c4_summary,
    description: TEXTS.c4_description,
    difficulty: 'beginner',
    starterPattern: '^#',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c4_cases[0], input: '#fff', expect: 'match' },
      { label: TEXTS.c4_cases[1], input: '#ABC', expect: 'match' },
      { label: TEXTS.c4_cases[2], input: '#abc123', expect: 'match' },
      { label: TEXTS.c4_cases[3], input: '#FfAa00', expect: 'match' },
      { label: TEXTS.c4_cases[4], input: 'fff', expect: 'noMatch' },
      { label: TEXTS.c4_cases[5], input: '#gggggg', expect: 'noMatch' },
      { label: TEXTS.c4_cases[6], input: '#1234', expect: 'noMatch' },
      { label: TEXTS.c4_cases[7], input: '#12345', expect: 'noMatch' },
    ],
    hints: TEXTS.c4_hints,
    idealSolution: {
      pattern: '^#([\\da-fA-F]{3}|[\\da-fA-F]{6})$',
      explanation: TEXTS.c4_explanation,
    },
  },
  {
    id: 'iso-date',
    title: TEXTS.c5_title,
    summary: TEXTS.c5_summary,
    description: TEXTS.c5_description,
    difficulty: 'beginner',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c5_cases[0], input: '2025-05-09', expect: 'match' },
      { label: TEXTS.c5_cases[1], input: '1990-01-01', expect: 'match' },
      { label: TEXTS.c5_cases[2], input: '2025-1-1', expect: 'noMatch' },
      { label: TEXTS.c5_cases[3], input: '2025/05/09', expect: 'noMatch' },
      { label: TEXTS.c5_cases[4], input: '2025-05-09extra', expect: 'noMatch' },
      { label: TEXTS.c5_cases[5], input: '', expect: 'noMatch' },
    ],
    hints: TEXTS.c5_hints,
    idealSolution: { pattern: '^\\d{4}-\\d{2}-\\d{2}$' },
  },
  {
    id: 'strong-password',
    title: TEXTS.c6_title,
    summary: TEXTS.c6_summary,
    description: TEXTS.c6_description,
    difficulty: 'advanced',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c6_cases[0], input: 'Abc12345', expect: 'match' },
      { label: TEXTS.c6_cases[1], input: 'longenoughpw1', expect: 'match' },
      { label: TEXTS.c6_cases[2], input: 'P@ssw0rd!', expect: 'match' },
      { label: TEXTS.c6_cases[3], input: 'Short1', expect: 'noMatch' },
      { label: TEXTS.c6_cases[4], input: 'alllowercase', expect: 'noMatch' },
      { label: TEXTS.c6_cases[5], input: '12345678', expect: 'noMatch' },
      { label: TEXTS.c6_cases[6], input: '', expect: 'noMatch' },
    ],
    hints: TEXTS.c6_hints,
    idealSolution: {
      pattern: '^(?=.*[A-Za-z])(?=.*\\d).{8,}$',
      explanation: TEXTS.c6_explanation,
    },
  },
  {
    id: 'phone-na',
    title: TEXTS.c7_title,
    summary: TEXTS.c7_summary,
    description: TEXTS.c7_description,
    difficulty: 'intermediate',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c7_cases[0], input: '(415) 555-2671', expect: 'match' },
      { label: TEXTS.c7_cases[1], input: '415-555-2671', expect: 'match' },
      { label: TEXTS.c7_cases[2], input: '415.555.2671', expect: 'match' },
      { label: TEXTS.c7_cases[3], input: '+1 415 555 2671', expect: 'match' },
      { label: TEXTS.c7_cases[4], input: '4155552671', expect: 'match' },
      { label: TEXTS.c7_cases[5], input: '415-55-2671', expect: 'noMatch' },
      { label: TEXTS.c7_cases[6], input: '415 555 26710', expect: 'noMatch' },
      { label: TEXTS.c7_cases[7], input: 'abc-def-ghij', expect: 'noMatch' },
      { label: TEXTS.c7_cases[8], input: '', expect: 'noMatch' },
    ],
    hints: TEXTS.c7_hints,
    idealSolution: {
      pattern: '^(?:\\+1[ -]?)?\\(?\\d{3}\\)?[ .-]?\\d{3}[ .-]?\\d{4}$',
      explanation: TEXTS.c7_explanation,
    },
  },
  {
    id: 'slug-url',
    title: TEXTS.c8_title,
    summary: TEXTS.c8_summary,
    description: TEXTS.c8_description,
    difficulty: 'intermediate',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c8_cases[0], input: 'hello', expect: 'match' },
      { label: TEXTS.c8_cases[1], input: 'hello-world', expect: 'match' },
      { label: TEXTS.c8_cases[2], input: 'my-cool-post-2024', expect: 'match' },
      { label: TEXTS.c8_cases[3], input: 'Hello-World', expect: 'noMatch' },
      { label: TEXTS.c8_cases[4], input: '-leading', expect: 'noMatch' },
      { label: TEXTS.c8_cases[5], input: 'trailing-', expect: 'noMatch' },
      { label: TEXTS.c8_cases[6], input: 'foo--bar', expect: 'noMatch' },
      { label: TEXTS.c8_cases[7], input: 'with space', expect: 'noMatch' },
      { label: TEXTS.c8_cases[8], input: '', expect: 'noMatch' },
    ],
    hints: TEXTS.c8_hints,
    idealSolution: {
      pattern: '^[a-z0-9]+(-[a-z0-9]+)*$',
      explanation: TEXTS.c8_explanation,
    },
  },
  {
    id: 'extract-md-link',
    title: TEXTS.c9_title,
    summary: TEXTS.c9_summary,
    description: TEXTS.c9_description,
    difficulty: 'intermediate',
    starterPattern: '',
    starterFlags: 'g',
    testCases: [
      { label: TEXTS.c9_cases[0], input: 'See [docs](https://example.com) please.', expect: 'match' },
      { label: TEXTS.c9_cases[1], input: '[a](http://x) and [b](http://y).', expect: 'match' },
      { label: TEXTS.c9_cases[2], input: '参考[维基百科](https://wiki.example/regex)。', expect: 'match' },
      { label: TEXTS.c9_cases[3], input: 'This is just plain text.', expect: 'noMatch' },
      { label: TEXTS.c9_cases[4], input: 'See [docs] for info.', expect: 'noMatch' },
      { label: TEXTS.c9_cases[5], input: 'broken: [text](unclosed', expect: 'noMatch' },
    ],
    hints: TEXTS.c9_hints,
    idealSolution: {
      pattern: '\\[([^\\]]+)\\]\\(([^)]+)\\)',
      flags: 'g',
      explanation: TEXTS.c9_explanation,
    },
  },
  {
    id: 'css-class',
    title: TEXTS.c10_title,
    summary: TEXTS.c10_summary,
    description: TEXTS.c10_description,
    difficulty: 'intermediate',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c10_cases[0], input: 'hero', expect: 'match' },
      { label: TEXTS.c10_cases[1], input: 'btn-primary', expect: 'match' },
      { label: TEXTS.c10_cases[2], input: '_internal', expect: 'match' },
      { label: TEXTS.c10_cases[3], input: '-debug', expect: 'match' },
      { label: TEXTS.c10_cases[4], input: 'Section1', expect: 'match' },
      { label: TEXTS.c10_cases[5], input: '1col', expect: 'noMatch' },
      { label: TEXTS.c10_cases[6], input: '--double-dash', expect: 'noMatch' },
      { label: TEXTS.c10_cases[7], input: 'with space', expect: 'noMatch' },
      { label: TEXTS.c10_cases[8], input: 'btn!', expect: 'noMatch' },
      { label: TEXTS.c10_cases[9], input: '', expect: 'noMatch' },
    ],
    hints: TEXTS.c10_hints,
    idealSolution: {
      pattern: '^-?[A-Za-z_][A-Za-z0-9_-]*$',
      explanation: TEXTS.c10_explanation,
    },
  },
  {
    id: 'uuid-v4',
    title: TEXTS.c11_title,
    summary: TEXTS.c11_summary,
    description: TEXTS.c11_description,
    difficulty: 'advanced',
    starterPattern: '^',
    starterFlags: '',
    testCases: [
      { label: TEXTS.c11_cases[0], input: '550e8400-e29b-41d4-a716-446655440000', expect: 'match' },
      { label: TEXTS.c11_cases[1], input: '123E4567-E89B-42D3-B456-426614174000', expect: 'match' },
      { label: TEXTS.c11_cases[2], input: 'f47ac10b-58cc-4372-a567-0e02b2c3d479', expect: 'match' },
      { label: TEXTS.c11_cases[3], input: '00000000-0000-1000-8000-000000000000', expect: 'noMatch' },
      { label: TEXTS.c11_cases[4], input: '550e8400-e29b-41d4-c716-446655440000', expect: 'noMatch' },
      { label: TEXTS.c11_cases[5], input: '550e8400-e29b-41d4-a716-44665544', expect: 'noMatch' },
      { label: TEXTS.c11_cases[6], input: '550e8400-e29b-41d4-a716-44665544000g', expect: 'noMatch' },
      { label: TEXTS.c11_cases[7], input: 'not-a-uuid-at-all', expect: 'noMatch' },
      { label: TEXTS.c11_cases[8], input: '', expect: 'noMatch' },
    ],
    hints: TEXTS.c11_hints,
    idealSolution: {
      pattern:
        '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$',
      explanation: TEXTS.c11_explanation,
    },
  },
];

export function findChallenge(id: string): Challenge | undefined {
  return CHALLENGES.find((c) => c.id === id);
}
