import type { PatternTemplate } from '../types/regex';

export const PATTERN_LIBRARY: PatternTemplate[] = [
  {
    name: 'Email Address',
    nameKey: 'plib_email_name',
    pattern: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',
    flags: 'g',
    description: 'Matches most common email address formats',
    descKey: 'plib_email_desc',
    category: 'Common',
    categoryKey: 'plib_cat_common',
  },
  {
    name: 'URL',
    nameKey: 'plib_url_name',
    pattern: 'https?:\\/\\/[\\w\\-]+(\\.[\\w\\-]+)+[\\w\\-.,@?^=%&:/~+#]*',
    flags: 'g',
    description: 'Matches HTTP and HTTPS URLs',
    descKey: 'plib_url_desc',
    category: 'Common',
    categoryKey: 'plib_cat_common',
  },
  {
    name: 'IPv4 Address',
    nameKey: 'plib_ipv4_name',
    pattern:
      '\\b(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\b',
    flags: 'g',
    description: 'Matches valid IPv4 addresses (0.0.0.0 to 255.255.255.255)',
    descKey: 'plib_ipv4_desc',
    category: 'Network',
    categoryKey: 'plib_cat_network',
  },
  {
    name: 'Phone Number (US)',
    nameKey: 'plib_phone_us_name',
    pattern: '(?:\\+?1[-.\\s]?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}',
    flags: 'g',
    description: 'Matches US phone numbers in various formats',
    descKey: 'plib_phone_us_desc',
    category: 'Common',
    categoryKey: 'plib_cat_common',
  },
  {
    name: 'Date (YYYY-MM-DD)',
    nameKey: 'plib_date_ymd_name',
    pattern: '\\d{4}[-/](?:0[1-9]|1[0-2])[-/](?:0[1-9]|[12]\\d|3[01])',
    flags: 'g',
    description: 'Matches dates in YYYY-MM-DD or YYYY/MM/DD format',
    descKey: 'plib_date_ymd_desc',
    category: 'Date & Time',
    categoryKey: 'plib_cat_datetime',
  },
  {
    name: 'Time (HH:MM:SS)',
    nameKey: 'plib_time_hms_name',
    pattern: '(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d)?',
    flags: 'g',
    description: 'Matches 24-hour time format',
    descKey: 'plib_time_hms_desc',
    category: 'Date & Time',
    categoryKey: 'plib_cat_datetime',
  },
  {
    name: 'Hex Color',
    nameKey: 'plib_hex_color_name',
    pattern: '#(?:[0-9a-fA-F]{3}){1,2}\\b',
    flags: 'g',
    description: 'Matches hex color codes (#RGB or #RRGGBB)',
    descKey: 'plib_hex_color_desc',
    category: 'Web',
    categoryKey: 'plib_cat_web',
  },
  {
    name: 'HTML Tag',
    nameKey: 'plib_html_tag_name',
    pattern: '<\\/?[a-zA-Z][a-zA-Z0-9]*(?:\\s[^>]*)?\\/?>',
    flags: 'g',
    description: 'Matches opening and closing HTML tags',
    descKey: 'plib_html_tag_desc',
    category: 'Web',
    categoryKey: 'plib_cat_web',
  },
  {
    name: 'Integer',
    nameKey: 'plib_integer_name',
    pattern: '-?\\d+',
    flags: 'g',
    description: 'Matches positive and negative integers',
    descKey: 'plib_integer_desc',
    category: 'Numbers',
    categoryKey: 'plib_cat_numbers',
  },
  {
    name: 'Decimal Number',
    nameKey: 'plib_decimal_name',
    pattern: '-?\\d+\\.\\d+',
    flags: 'g',
    description: 'Matches decimal numbers',
    descKey: 'plib_decimal_desc',
    category: 'Numbers',
    categoryKey: 'plib_cat_numbers',
  },
  {
    name: 'Username',
    nameKey: 'plib_username_name',
    pattern: '[a-zA-Z0-9_-]{3,16}',
    flags: 'g',
    description: 'Matches usernames (3-16 alphanumeric, underscore, hyphen)',
    descKey: 'plib_username_desc',
    category: 'Validation',
    categoryKey: 'plib_cat_validation',
  },
  {
    name: 'Strong Password',
    nameKey: 'plib_strong_pwd_name',
    pattern: '(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}',
    flags: '',
    description: 'At least 8 chars, one uppercase, lowercase, digit, and special character',
    descKey: 'plib_strong_pwd_desc',
    category: 'Validation',
    categoryKey: 'plib_cat_validation',
  },
  {
    name: 'Chinese Characters',
    nameKey: 'plib_chinese_name',
    pattern: '[\\u4e00-\\u9fa5]+',
    flags: 'g',
    description: 'Matches sequences of Chinese characters',
    descKey: 'plib_chinese_desc',
    category: 'Unicode',
    categoryKey: 'plib_cat_unicode',
  },
  {
    name: 'Whitespace Trimmer',
    nameKey: 'plib_ws_trim_name',
    pattern: '^\\s+|\\s+$',
    flags: 'gm',
    description: 'Matches leading and trailing whitespace',
    descKey: 'plib_ws_trim_desc',
    category: 'Text',
    categoryKey: 'plib_cat_text',
  },
  {
    name: 'Duplicate Words',
    nameKey: 'plib_dup_words_name',
    pattern: '\\b(\\w+)\\s+\\1\\b',
    flags: 'gi',
    description: 'Finds consecutive duplicate words',
    descKey: 'plib_dup_words_desc',
    category: 'Text',
    categoryKey: 'plib_cat_text',
  },
];

export function getCategories(): string[] {
  const cats = new Set(PATTERN_LIBRARY.map((p) => p.category));
  return Array.from(cats);
}
